# Generated by Django 4.1.4 on 2022-12-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Пост')),
                ('image', models.ImageField(default='-', upload_to='', verbose_name='Фото')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('categoryies', models.ManyToManyField(related_name='category', to='core.category')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('topic', 'date'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=255, verbose_name='Пол')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('about', models.TextField(verbose_name='О себе')),
                ('photo', models.ImageField(default='-', upload_to='', verbose_name='Фото')),
                ('post', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='core.post')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('first_name', 'last_name'),
            },
        ),
    ]
