# Generated by Django 4.0.5 on 2022-11-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='-', upload_to='', verbose_name='Фото'),
        ),
    ]
