# Generated by Django 4.0.5 on 2022-11-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='core.post'),
        ),
    ]
