# Generated by Django 4.1.4 on 2022-12-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='core.user'),
        ),
    ]
