# Generated by Django 4.1.4 on 2023-01-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='-', upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
